#!/bin/bash
#SBATCH --mem=16g
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1    # <- match to OMP_NUM_THREADS
#SBATCH --partition=gpu      # <- or cpu_amd, gpu_a100
#SBATCH --gpus-per-node=1
#SBATCH --gpu-bind=closest
#SBATCH --account=bgtj-tgirails
#SBATCH --time=1:00:00      # hh:mm:ss for the job
##SBATCH --mail-user=leca5365@colorado.edu
##SBATCH --mail-type="BEGIN,END" See sbatch or srun man pages for more email options
#SBATCH --output=slurm_logs/%x_%A_%a.out
#SBATCH --job-name=chelsa-runs
#SBATCH --array=0-11 #<==== CHANGE THIS TO THE APPROPRIATE RANGE

set -x
export OMP_NUM_THREADS=1

cd /u/kplane19/torchgeo-bench/src/torchgeo_bench/coordbench/scripts/
source /u/kplane19/torchgeo-benc/.venv/bin/activate

torchgeo-bench coord --model climplicit --dataset usa_electric_usage --split both --device cuda:0 \
--from-polygon --spatial-aggregation-methods median_and_iqr \
--output results/coordbench_electric_load_polygon_test.csv "$@"